adds shell.nix
unixporn/trup-rs pull request #25
Opened 2021-03-23 10:35 UTC by legendofmiracles

@buffet i was asked to ask you to check if it's alright

2021-03-26 22:59 UTC, buffet reviewed
Do you need rustc when you have cargo in there?

openssl should be buildInputs (non-native), not sure sqlx, I assume it gets used in the build process, so should be fine.

2021-03-27 15:27 UTC, legendofmiracles commented
Yes you do need rustc, in case you have another version installed outside the nix-shell. As far as I am aware it also doesn't really add more dependencies, as cargo and rustc already point to the same version. 

And sqlx-cli isn't necessarily needed for building, only for changing the DB. So I'm unsure where to put that.

2021-03-27 17:42 UTC, fortuneteller2k requested changes
runtime dependencies should be in `buildInputs`

2021-03-27 17:42 UTC, fortuneteller2k commented on shell.nix
> +          nativeBuildInputs = with pkgs; [ rustc cargo gcc openssl pkg-config sqlx-cli ];
```suggestion
          nativeBuildInputs = with pkgs; [ rustc cargo gcc openssl pkg-config ];
          
          buildInputs = with pkgs; [ sqlx-cli ];
```

2021-03-27 18:56 UTC, legendofmiracles commented
Ok cool! Thank you so much!

2021-03-28 01:37 UTC, fortuneteller2k approved these changes

2021-03-28 10:50 UTC, merged

2021-03-28 10:50 UTC, elkowar commented
Epic, thanks! Also thanks to @buffet for the review

2021-03-28 10:56 UTC, legendofmiracles commented
And @fortuneteller2k.